---
title: "Arbejdsmarkedet"
author: "Johan Bysted"
date: "2024-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Indhent data for labor force:

```{r}
library(readxl)
library(ggplot2)
library(tidyr)
library(dplyr)
library(readr)
lafo <- read_excel("Makroøkonomisk projekt.xlsx", sheet="Labor force")
yr <- lafo$Year; sz <- lafo$`Labor Force size`
df <- data.frame(lafo$Year, lafo$`Labor Force size`)
br <- lafo$Branche; ma <- lafo$Mangel
vi <- lafo$Branche2; pct <- lafo$Pct2
```


```{r}
ggplot(df, aes(x = yr, y = sz), ylim=c(35000000,55000000)) +
  geom_line(aes(group=1), col="blue")+
  scale_x_discrete(breaks=seq(min(yr), max(yr), by=2))+
  scale_y_continuous(labels = function(x) paste0(x/1000000, " million"))+
  labs(x = "Årstal", y = "Arbejdsstyrken i personer") +
  theme_minimal()
```
Mangel på arbejdskraft, 2026
```{r}
ggplot(lafo, aes(x=br, y=ma))+
  geom_bar(stat="identity", fill="blue", width=0.5)+
  labs(x="Branche", y="Mangel i personer")+ 
  theme_minimal()+
  theme(axis.text.x=element_text(size=11.5))
```


Virksomheder der oplever mangel på arbejdskraft
```{r}
ggplot(lafo, aes(x=vi, y=pct))+
  geom_bar(stat="identity", fill="red", width=0.5)+
  labs(x="Industri", y="Pct. af virksomheder")+
  theme_minimal()
```

