---
title: "Debt Brake"
author: "Viktor Damm"
date: "2024-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readxl)
library(ggplot2)
debt <- read_excel("Makroøkonomisk projekt.xlsx", sheet = "Debt ")
na.omit(debt)
date01 <- debt$Date...2
```

```{r}
ggplot(debt, aes(x = date01)) +
  geom_line(aes(y = `Percent of GDP...3`, color = "Tyskland"), linetype = "solid") +
  geom_line(aes(y = `Percent of GDP...18`, color = "EU"), linetype = "solid") + 
  geom_point(data = subset(debt, date01 >= as.Date("2024-01-01") & date01 <= as.Date("2028-01-01")),
             aes(x = date01, y = `Percent of GDP...3`, color = "Tyskland")) +
  labs(title = "",
       x = "År",
       y = "Pct. af BNP") +
  scale_color_manual(values = c("Tyskland" = "blue")) + # Fjern farven for EU
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position = "top") +
  labs(color = "Variable") +
  guides(color = guide_legend(title = NULL)) + 
  geom_abline(aes(intercept=0, slope=0)) +
  scale_x_date(date_breaks = "1 year", date_labels = "%Y")
```

```{r}
ger <- debt$`Percent of GDP...3`
eu <- debt$`Percent of GDP...18`
year <- 2000:2028
df <- data.frame(year, ger)
df <- df %>%
  mutate(data_type=ifelse(year<=2023, "Faktisk", "Forecast"))
eu_df <- data.frame(year = 2000:2023, ger = eu)

ggplot(df, aes(x = year, y = ger, linetype = data_type)) +
  geom_line(color = c("blue")) +
  scale_linetype_manual(values = c("solid", "dashed")) +
  labs(title = "Data and Forecast", x = "Year", y = "Value") +
  theme_minimal()
geom_line(data=eu_df,aes(x=year, y=ger), color="red")
```

```{r}
ggplot() +
  geom_line(data = df, aes(x = year, y = ger, linetype = data_type), color = c("blue")) +  # Adjust colors as needed
  geom_line(data = eu, aes(x = year, y = eu), color = "red") +  # Add another line
  scale_linetype_manual(values = c("solid", "dashed")) +  # Adjust linetypes as needed
  labs(title = "Data and Forecast", x = "Year", y = "Value") +
  theme_minimal()
```


```{r}
ggplot(debt, aes(x = date01)) +
  geom_line(aes(y = debt$`Percent of GDP...9`, color = "Tyskland"), linetype = "solid") +
  geom_line(aes(y = debt$`Percent of GDP...15`, color = "EU"), linetype = "solid") + # Tilføjelse af linje for enhedslønomkostninger
  labs(title = "",
       x = "År",
       y = "Pct. af BNP") +
  scale_color_manual(values = c("Tyskland" = "blue", "EU" = "red")) +  # Justér farverne efter behov
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(legend.position=c("top")) +
  labs(color = "Variable") +
  guides(color = guide_legend(title = NULL))
```

```{r}
date1 <- debt$Date...5
projectionbudget1 <- debt$`Percent of GDP...6`
date2 <- debt$Date...11
projection2 <- debt$`Percent of GDP...12`
ggplot(debt, aes(x = date1, y = projectionbudget1)) +
  geom_line(color = "blue") +
  labs(
       x = "År",
       y = "Procent af BNP") +
  theme_minimal()
ggplot(debt, aes(x = date2, y = projection2)) +
  geom_line(color = "blue") +
  labs(
       x = "År",
       y = "Procent af BNP") +
  theme_minimal()
```