---
title: "ECM-modeller"
author: "Johan Bysted"
date: "2024-05-07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ecm); library(tseries); library(dynlm);library(bimets)
```


```{r}
data <- read_excel("Makroøkonomisk projekt.xlsx", sheet = "Nominel nøgletal")
data_1 <- read_excel("Makroøkonomisk projekt.xlsx")

# Extract specific columns
USA_nom <- data$`Real Gross Domestic Product, Billions of Chained 2017 Dollars, Quarterly, Seasonally Adjusted Annual Rate`
exp_nom <- data$`In millions, Exports of Goods and Services in Germany, Chained 2010 Euros, Quarterly, Seasonally Adjusted`
ger_nom <- data$`Real Gross Domestic Product for Germany, Millions of Chained 2010 Euros, Quarterly, Seasonally Adjusted`
rente <- data_1$`Interest Rate (10-year Goverment Bond Yields)`
inf <- data_1$`HCIP: growth same period previous year`
ULC <- data_1$`ULC pct change previous period`
euro_nom <- data$`Real Gross Domestic Product (Euro/ECU Series) for Euro Area (19 Countries)`

# Convert columns to time series separately
USA_nom_ts <- ts(USA_nom, start = c(2000, 1), end = c(2023, 4), frequency = 4)
exp_nom_ts <- ts(exp_nom, start = c(2000, 1), end = c(2023, 4), frequency = 4)
ger_nom_ts <- ts(ger_nom, start = c(2000, 1), end = c(2023, 4), frequency = 4)
rente_ts <- ts(rente, start = c(2000, 1), end = c(2023, 4), frequency = 4)
inf_ts <- ts(inf, start = c(2000, 1), end = c(2023, 4), frequency = 4)
ULC_ts <- ts(ULC, start = c(2000, 1), end = c(2023, 4), frequency = 4)
euro_nom_ts <- ts(euro_nom, start = c(2000, 1), end = c(2023, 4), frequency = 4)
fx_ts <- ts(fx, start = c(2000, 1), end = c(2023, 4), frequency = 4)
```

```{r}
ECM <- dynlm(TSDELTALOG(ger_nom_ts)~L(TSDELTALOG(USA_nom_ts,1))+L(TSDELTALOG(euro_nom_ts))+L(rente_ts,6)+L(ULC_ts,3)+L(log(USA_nom_ts),1)+log(L(euro_nom_ts,1))+L(log(ger_nom_ts),1))
summary(ECM)
```

