---
title: "Forelæsning 3"
author: "Viktor Damm"
date: "2024-11-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library()
```

```{r}
library(readxl)
DISKO <- read_excel("DISKO_mikro5.xls")
```

```{r}
#Payoff til rækksepiller når hun møder kolonne.
#Pay-off matricen er symmetrisk så man behøver ikke specificere resten

Payoff.matrice <- matrix(c(2, 2, -2, -1, 0, 2, 1, -3 ,1), nrow=3,  ncol=3) 
rownames(Payoff.matrice)<-c("Offensiv","Defensiv","Imitativ")
colnames(Payoff.matrice)<-c("Offensiv","Defensiv","Imitativ")
Payoff.matrice

#Vælg proportionerne, der skal være offensiv og defensiv fra start
#Resten bliver så automatisk imitative
s.off<-0.1
s.def<-0.1

#Vælg hvor mange runder simulationen skal køre
runder<-10

#Simulationsmodellen består grundlæggende af to matricer.
#En (props) har tre kolonner og indeholder proprotionen af virksomehder, der følger hver strategi.
#Den har en række for hver runde
#Her er start-runden

props<-t(rep(0,3))
props[1]<-s.off
props[2]<-s.def
props[3]<-1-s.off-s.def
props<-as.matrix(props)
props

#Den anden (payoffs) har også en række for hver runde, men har 4 kolonner
#En for payoff til hver strategi og en for gennemsnits-payoff
#Her er første runde

#Det ser besværligt ud, men payoffs er bare bestemt som i klassisk spilteori, jf slides.
payoffs<-t(rep(0,4))
payoffs[1]<-Payoff.matrice[1,1]*props[1]+Payoff.matrice[1,2]*props[2]+Payoff.matrice[1,3]*props[3]
payoffs[2]<-Payoff.matrice[2,1]*props[1]+Payoff.matrice[2,2]*props[2]+Payoff.matrice[2,3]*props[3]
payoffs[3]<-Payoff.matrice[3,1]*props[1]+Payoff.matrice[3,2]*props[2]+Payoff.matrice[3,3]*props[3]
payoffs[4]<-payoffs[1]*props[1]+payoffs[2]*props[2]+payoffs[3]*props[3]
payoffs<-as.matrix(payoffs)
payoffs

#Nu skal vi 'klistre' en række på hver matrice for hver runde simulationen skal køre
#Først laver vi en tidsvariabel, som starter med værdien 1, og bremsen, der styrer længden på et tids-skridt
#Replikatorligningen fra slides bestemmer nye andele
#Payoffs er stadig bestemt som i den klassiske analyse
bremse<-0.25
t<-1
while(t<runder){
  new.props <- t(rep(0,3))
  new.props[1] <- props[t,1]+props[t,1]*(payoffs[t,1]-payoffs[t,4])*bremse
  new.props[2] <- props[t,2]+props[t,2]*(payoffs[t,2]-payoffs[t,4])*bremse
  new.props[3] <- props[t,3]+props[t,3]*(payoffs[t,3]-payoffs[t,4])*bremse
  props<-rbind(props,new.props)
  
  new.payoffs<-t(rep(0,4))
  new.payoffs[1]<-Payoff.matrice[1,1]*props[t+1,1]+Payoff.matrice[1,2]*props[t+1,2]+Payoff.matrice[1,3]*props[t+1,3]
  new.payoffs[2]<-Payoff.matrice[2,1]*props[t+1,1]+Payoff.matrice[2,2]*props[t+1,2]+Payoff.matrice[2,3]*props[t+1,3]
  new.payoffs[3]<-Payoff.matrice[3,1]*props[t+1,1]+Payoff.matrice[3,2]*props[t+1,2]+Payoff.matrice[3,3]*props[t+1,3]
  new.payoffs[4]<-new.payoffs[1]*props[t+1,1]+new.payoffs[2]*props[t+1,2]+new.payoffs[3]*props[t+1,3]
  payoffs<-rbind(payoffs,new.payoffs)
  
  t<-t+1
}

#Nu har vi kørt simulationen af konkurrence i det antal perioder, vi valgte.
props
payoffs
#Den følgende kode laver en fin graf over resultatet

outdata<-cbind(props,payoffs,c(1:runder))
colnames(outdata)<-c("prop.off","prop.def","prop.imi","pay.off","pay.def","pay.imi","pay.av","runde")

a<-as.data.frame(outdata)
par(new=F)
plot(x=a$runde,y=a$prop.off,xlim=c(0,runder),ylim=c(0,1), xlab='tid', ylab='andel med strategi',
     type = "l", col="red", main="Off/def/Imi -- Red/Green/Blue")
par(new=T)
plot(x=a$runde,y=a$prop.def,xlim=c(0,runder),ylim=c(0,1), xlab='', ylab='',type = "l", col="green")
par(new=T)
plot(x=a$runde,y=a$prop.imi,xlim=c(0,runder),ylim=c(0,1), xlab='', ylab='',type = "l", col="blue")

#Alternativ: pak koden ind i en 'funktion' i R,
# så man nemmere kan køre simulationer med andre parametre.
# (initial-proportioner, bremse og antal runder)
```

```{r}

Payoff.matrice <- matrix(c(2, 2, -2, -1, 0, 2, 1, -3 ,1), nrow=3,  ncol=3) 
rownames(Payoff.matrice)<-c("Offensiv","Defensiv","Imitativ")
colnames(Payoff.matrice)<-c("Offensiv","Defensiv","Imitativ")
Payoff.matrice


#Herunder kører spillet. Man skal definere antal runder samt start proportioner for off og def
#Imitativ bestemmes automatisk som resten. Derudover skal man sætte en bremse for at få flotte figurer
#Man kan sige, at bremsen bestemmer hvor lang "tid" en runde er 

konkurrence <- function(runder,s.off,s.def,bremse){
  props<-t(rep(0,3))
  props[1]<-s.off
  props[2]<-s.def
  props[3]<-1-s.off-s.def
  props<-as.matrix(props)
  
  #Payoffs bestemmes som i klassisk spilteori
  payoffs<-t(rep(0,4))
  payoffs[1]<-Payoff.matrice[1,1]*props[1]+Payoff.matrice[1,2]*props[2]+Payoff.matrice[1,3]*props[3]
  payoffs[2]<-Payoff.matrice[2,1]*props[1]+Payoff.matrice[2,2]*props[2]+Payoff.matrice[2,3]*props[3]
  payoffs[3]<-Payoff.matrice[3,1]*props[1]+Payoff.matrice[3,2]*props[2]+Payoff.matrice[3,3]*props[3]
  payoffs[4]<-payoffs[1]*props[1]+payoffs[2]*props[2]+payoffs[3]*props[3]
  payoffs<-as.matrix(payoffs)
  
  #Den forudgående kode er for første runde
  #Koden herunde skriver en ny linje data på for hver runde
  t<-1
  while(t<runder){
    new.props <- t(rep(0,3))
    new.props[1] <- props[t,1]+props[t,1]*(payoffs[t,1]-payoffs[t,4])*bremse
    new.props[2] <- props[t,2]+props[t,2]*(payoffs[t,2]-payoffs[t,4])*bremse
    new.props[3] <- props[t,3]+props[t,3]*(payoffs[t,3]-payoffs[t,4])*bremse
    props<-rbind(props,new.props)
    
    new.payoffs<-t(rep(0,4))
    new.payoffs[1]<-Payoff.matrice[1,1]*props[t+1,1]+Payoff.matrice[1,2]*props[t+1,2]+Payoff.matrice[1,3]*props[t+1,3]
    new.payoffs[2]<-Payoff.matrice[2,1]*props[t+1,1]+Payoff.matrice[2,2]*props[t+1,2]+Payoff.matrice[2,3]*props[t+1,3]
    new.payoffs[3]<-Payoff.matrice[3,1]*props[t+1,1]+Payoff.matrice[3,2]*props[t+1,2]+Payoff.matrice[3,3]*props[t+1,3]
    new.payoffs[4]<-new.payoffs[1]*props[t+1,1]+new.payoffs[2]*props[t+1,2]+new.payoffs[3]*props[t+1,3]
    payoffs<-rbind(payoffs,new.payoffs)
    
    t<-t+1
  }
  outdata<-cbind(props,payoffs,c(1:runder))
  colnames(outdata)<-c("prop.off","prop.def","prop.imi","pay.off","pay.def","pay.imi","pay.av","runde")

  a<-as.data.frame(outdata)
  par(new=F)
  plot(x=a$runde,y=a$prop.off,xlim=c(0,runder),ylim=c(0,1), xlab='tid', ylab='andel med strategi',
       type = "l", col="red", main="Off/def/Imi -- Red/Green/Blue")
  par(new=T)
  plot(x=a$runde,y=a$prop.def,xlim=c(0,runder),ylim=c(0,1), xlab='', ylab='',type = "l", col="green")
  par(new=T)
  plot(x=a$runde,y=a$prop.imi,xlim=c(0,runder),ylim=c(0,1), xlab='', ylab='',type = "l", col="blue")
  
}

#Stabil
konkurrence(19,0.375,0.500,0.25)
#Lille ændring fra ligevægt
konkurrence(19,0.380,0.495,0.25)
#Bytter startandele om
konkurrence(19,0.500,0.375,0.25)
#I bølger
konkurrence(19,0.200,0.700,0.25)
```

