---
title: "Regression"
author: ""
date: "2024-04-12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(dynlm)
library(lmtest)
library(dplyr)
data <- read_excel("Makroøkonomisk projekt.xlsx")
gdp <- data$gdp_pct_change
china <- data$`China: Real GDP growth quarterly previous period (National Bureau of Statistics of China)`
unemp <- data$unemp
inf <- data$`HPI: growth same period previous year`
pri_con <- data$`Real private consumption: https://fred.stlouisfed.org/series/NAEXKP02DEQ657S`
energy <- data$`Consumer Price Index: OECD Groups: Energy (Fuel, Electricity, and Gasoline): Total for Germany, Change, Growth rate same period previous year, Quarterly, Not Seasonally Adjusted`
gdp_yearago<-data$`Real GDP percent year ago`
eurozone<-data$`Eurozonen: Real GDP growth quarterly previous period`
fx<- data$`Exchange rate`
exp <- data$`Real Export - % change from year ago`
rente <- data$`Interest Rate (10-year Goverment Bond Yields)`
G <- data$`Germany Fiscal Expenditure EUR Billion.`
ULC<-data$`ULC pct change previous period`
produktivitet<-data$`Productivity output per hour worked (mining and manufacturing)`
import<-data$`Real Import - % change from year ago`
USA<-data$`USA real gdp percent year ago`
eurozone_pct_year<-data$`New eurozone gdp year ago`
```

Regressionsmodel for BNP
```{r}
mod <- lm(gdp_yearago~exp+inf+lag(energy,4)+rente+unemp)
plot(mod, which=1)
hist(residuals(mod))
bptest(mod)
summary(mod)
```


```{r}
mod2 <- lm(gdp_yearago~exp+inf+lag(energy,4)+lag(rente,4)+eurozone+unemp+import+log(produktivitet)+ULC+fx)
plot(mod, which=1)
hist(residuals(mod))
bptest(mod)
summary(mod)
```

Model som godt kan bruges (mangler USA data og tjek eurozone skal være year ago)
```{r}
model_standard <- lm(gdp_yearago~exp+rente+lag(ULC,3)+eurozone+china)
plot(model_standard, which=2)
hist(residuals(model_standard))
bptest(model_standard)
summary(model_standard)
```


Argumentet for at vi undlader arbejdsløsheden
```{r}
plot(unemp, type = "l", col = "blue", ylim = c(-10, 15),)
lines(gdp_yearago)
```


NYT FORSØG hvor vi finder ud af at det ikke giver mening med hverken inflation eller energy
```{r}
nytforsøg<-lm(gdp_yearago~exp+lag(rente,6)+lag(ULC,3)+lag(china,1)+lag(USA,1)+eurozone_pct_year)
summary(nytforsøg)
```


Forsøg med eksport som afhængig variabel
```{r}
reg_eksport<-lm(exp~ULC)
summary(reg_eksport)
```



```{r}
plot(gdp, ylim=c(-15,15), type="l", col="blue")
lines(exp, type="l", col="red")
lines(100*gov_con_log[1:96], type="l", col="black")
lines(energy, type="l", col="green")
energy <- na.omit(energy)
```

Procentvis ændring for gov exp
```{r}
gov_con_log <- c(NA, diff(gov_con)/lag(gov_con))
gov_con_log <- gov_con_log[2:97]
```



Regressionsmodel for export
```{r}
reg_exp <- lm(exp[1:90] ~ china[1:90] + lag(energy[1:90], 2))
summary(reg_exp)
```


```{r}
 # Libraries for dynamic lm, regression table and F tests
library(dynlm);library(lmtest);library(car)
data(data, package=’wooldridge’)# Define Yearly time series beginning in 1913
tsdata <- ts(fertil3, start=1913) # Linear regression of model with lags:
res <- dynlm(gfr ~ pe + L(pe) + L(pe,2) + ww2 + pill, data=tsdata)
coeftest(res)
```


```{r}
plot(exp, type="l", col="blue")
lines(USA)
```



