name: Update Excel Data

on:
  push:
    branches:
      - main

jobs:
  update_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2
      with:
        dockerfile: |
          FROM rocker/r-ver:4.3.3

    - name: Install required R packages
      run: |
        install.packages("readxl")
        install.packages("httr")
        install.packages("RCurl")

    - name: Download Excel file from OneDrive
      run: |
        library(readxl)
        library(httr)
        library(RCurl)
        
        onedrive_url <- "https://aaudk-my.sharepoint.com/:x:/r/personal/ci65gm_student_aau_dk/Documents/%C3%98konomi/4.%20semester/Projekt/Makro%C3%B8konomisk%20projekt.xlsx?d=w01eca2b5d0dd450c8f50be290c545992&csf=1&web=1&e=Nzn7Wr&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0"
        
        # Extract direct download link from OneDrive URL
        response <- GET(onedrive_url)
        download_url <- content(response)$location
        
        # Download Excel file
        download.file(download_url, "data.xlsx", mode = "wb")
        
    - name: Commit and push updated data to repository
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add data.xlsx
        git commit -m "Update Excel data"
        git push
